#!/bin/sh
# Выборка только js файлов
files=$(git diff --cached --name-only --diff-filter=ACM | grep "\.js$")
if [ "$files" = "" ]; then
    exit 0
fi

pass=true

echo "Validating JavaScript:"

# Проверяем все файлы
# TODO async file check
for file in ${files}; do
    # Проверка по jshint
    result=$(jshint ${file})
    if [ "$result" == "" ]; then
        echo "JSHint Passed: ${file}"
    else
        echo "JSHint Failed: ${file}"
        echo "$result"
        pass=false
    fi

    # Проверка по jscs
    result=$(jscs ${file})
    if [ "$result" == "" ]; then
        echo "JSCS Passed: ${file}"
    else
        echo "JSCS Failed: ${file}"
        echo "$result"
        pass=false
    fi
done

echo "JavaScript validation complete"

# Вывод результата проверки
if ! $pass; then
    echo "COMMIT FAILED: Your commit contains files that should pass JSCS & JSHint but do not. Please fix errors and try again."
    exit 1
else
    echo "COMMIT SUCCEEDED"
fi