name: Build APK

on:
  push:
    branches: [ feature-test-stand-update ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install ember and bower
      run: |
       set -x
       node -v
       npm install -g bower
       npm install -g ember-cli@2.4.3
       yarn install
       bower install

    - name: Build Cordova
      with:
        exec: |
          cd FlexberryGisTestStand.Cordova/FlexberryGisTestStand.Cordova && \
          cordova platform add android && \
          cp "/templates/ConfigXmlParser.java" "/platforms/android/CordovaLib/src/org/apache/cordova/ConfigXmlParser.java" && \
          cp "/templates/AndroidManifest.xml" "/platforms/android/app/src/main/AndroidManifest.xml" && \
          cordova build android --packageType=apk .
